name: Release and publish package
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        default: patch
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm run build

  create-tag:
    name: Create new tag
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git version ${{ github.event.inputs.version }}
      - uses: codex-team/action-nodejs-package-info@v1
      - run: git tag ${{ steps.package.outputs.version }}
      - run: git push origin main --tags

  create-release:
    name: Create new release
    needs: create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: codex-team/action-nodejs-package-info@v1
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.package.outputs.version }}
          token: ${{ secrets.GPR_AUTH_TOKEN }}

  publish-gpr:
    name: Publish to github package registry
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: npm run build
      - run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_AUTH_TOKEN }}
      - run: npm publish
