name: Build and Deploy storybook
on:
  push:
    paths: ["src/components/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3 # Docs: https://github.com/actions/checkout
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: temp-docs # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: ../../docs # The folder that we serve our Storybook files from

