name: Build and Deploy storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Docs: https://github.com/actions/checkout
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm i
          npm run build-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0 # Docs: https://github.com/JamesIves/github-pages-deploy-action
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder that the build-storybook script generates files.
          # clean: true
          # target-folder: docs
